modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/CAS-ual-TY/DuplicateEntityUUIDFix/issues"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="https://github.com/CAS-ual-TY/DuplicateEntityUUIDFix"
    logoFile="logo.png"
    credits="Mojang and the NeoForged Team"
    authors="${mod_authors}"
    displayTest="MATCH_VERSION"
    description='''${mod_description}'''

[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    mandatory=true #mandatory
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
