modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"
issueTrackerURL="https://github.com/CAS-ual-TY/DuplicateEntityUUIDFix/issues"

[[mods]]
    modId="deuf"
    version="${file.jarVersion}"
    displayName="DEUF - Duplicate Entity UUID Fix"
    displayURL="https://github.com/CAS-ual-TY/DuplicateEntityUUIDFix"
    logoFile="logo.png"
    credits="Mojang and the Minecraft Forge Team"
    authors="CAS_ual_TY"
    description="Changes UUIDs of loaded Entities in case their UUIDs are already assigned (and removes log spam)."
