modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/CAS-ual-TY/DuplicateEntityUUIDFix/issues" #optional

[[mods]] #mandatory
    modId="deuf" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="DEUF - Duplicate Entity UUID Fix" #mandatory
    #updateJSONURL="http://myurl.me/" #optional
    displayURL="https://github.com/CAS-ual-TY/DuplicateEntityUUIDFix" #optional
    logoFile="logo.png" #optional
    credits="Thanks for this example mod goes to Java" #optional
    authors="CAS_ual_TY" #optional
    description="Changes UUIDs of loaded Entities in case their UUIDs are already assigned (and removes log spam)."
